/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Conexion;
import Clases.DAL;
import Clases.DynamicButton;
import Clases.ObjetoCasas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**             
 *
 * @author panay
 */
public class Croquis extends javax.swing.JInternalFrame {

    /**
     * Creates new form Croquis
     */
    private List<DynamicButton> Casas;
    private int indice=0;
    public Croquis() {
        initComponents();
        cargarcasas();
    }
private void cargarcasas(){
     try {
            List<ObjetoCasas> M=DAL.ObtenerCasas(Conexion.getConexion()); 
              Casas=new ArrayList<>();
            for(ObjetoCasas t : M){
          
            DynamicButton casa=new DynamicButton("Casa"+t.GetIdCasas());
            casa.Setnumerocasa(t.GetIdCasas());
            casa.Setestadocasa(t.GetIdEstado());
            casa.addActionListener((ActionEvent Arg0) -> {
                
                
               
                try {
                    DynamicButton neobject=(DynamicButton)(Arg0.getSource());
                    ObjetoCasas ll=DAL.ObtenerCasasPorId(Conexion.getConexion(), neobject.getnumerocasa());
                    JPanel a=ll.GetallData();
                   PanelInfo.removeAll();
                   PanelInfo.repaint();
                    a.setSize(PanelInfo.getSize());
                   
                    PanelInfo.add(a);
                   PanelInfo.updateUI();
                } catch (SQLException ex) {
                    Logger.getLogger(Croquis.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                // aquí el código que quieres ejecutar cuando el botón sea presionado
                
            });
            jPanel1.add(casa);
            indice++;
            Casas.add(casa);
            }
            
            jPanel1.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(Croquis.class.getName()).log(Level.SEVERE, null, ex);
        }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        PanelInfo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1366, 684));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(0, 8));
        jScrollPane1.setViewportView(jPanel1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 720, 440));

        PanelInfo.setBackground(new java.awt.Color(153, 153, 153));
        PanelInfo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jPanel2.add(PanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 530, 180));

        jLabel12.setBackground(new java.awt.Color(153, 153, 153));
        jLabel12.setFont(new java.awt.Font("Modern No. 20", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(75, 123, 125));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cro.png"))); // NOI18N
        jLabel12.setText("                                   VISITAS");
        jLabel12.setOpaque(true);
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 70));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 123, 125));
        jLabel1.setText("Detalle Casa");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Planos.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 510, 270));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
