/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

//Importo la libreria de las animaciones
import AppPackage.AnimationClass;
import Clases.Conexion;
import Clases.DAL;
import Clases.EncriptarContrasena;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author panay
 */
public class Login1 extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    Conexion cn = new Conexion(); DAL da = new DAL();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondologin = new javax.swing.JPanel();
        jpLogin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtContraseña = new javax.swing.JPasswordField();
        jbtnEntrar = new javax.swing.JButton();
        jbtnRecuperar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPublic1 = new javax.swing.JLabel();
        jPalo1 = new javax.swing.JLabel();
        jPalo = new javax.swing.JLabel();
        jPublic = new javax.swing.JLabel();
        jblCerrar = new javax.swing.JLabel();
        jblMinimizar = new javax.swing.JLabel();

        javax.swing.GroupLayout jFondologinLayout = new javax.swing.GroupLayout(jFondologin);
        jFondologin.setLayout(jFondologinLayout);
        jFondologinLayout.setHorizontalGroup(
            jFondologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jFondologinLayout.setVerticalGroup(
            jFondologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogin.setBackground(new java.awt.Color(255, 255, 255));
        jpLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLoginMouseClicked(evt);
            }
        });
        jpLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 123, 125));
        jLabel5.setText("Contraseña:");
        jpLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(75, 123, 125));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton-redondo-con-usuario-en-el-interior (1).png"))); // NOI18N
        jpLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 70, -1));

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(75, 123, 125));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loginn.png"))); // NOI18N
        jLabel4.setText("INICIAR SESION");
        jLabel4.setVerifyInputWhenFocusTarget(false);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jpLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 290, 480, 40));

        jtxtUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jtxtUsuario.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 123, 125), 3));
        jpLogin.add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 210, 30));

        jtxtContraseña.setBackground(new java.awt.Color(51, 51, 51));
        jtxtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jtxtContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 123, 125), 3));
        jtxtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtContraseñaMouseClicked(evt);
            }
        });
        jpLogin.add(jtxtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 210, 30));

        jbtnEntrar.setBackground(new java.awt.Color(51, 51, 51));
        jbtnEntrar.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jbtnEntrar.setForeground(new java.awt.Color(75, 123, 125));
        jbtnEntrar.setText("ENTRAR");
        jbtnEntrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 123, 125), 3));
        jbtnEntrar.setContentAreaFilled(false);
        jbtnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnEntrarMouseClicked(evt);
            }
        });
        jbtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEntrarActionPerformed(evt);
            }
        });
        jpLogin.add(jbtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 90, 30));

        jbtnRecuperar.setBackground(new java.awt.Color(51, 51, 51));
        jbtnRecuperar.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jbtnRecuperar.setForeground(new java.awt.Color(75, 123, 125));
        jbtnRecuperar.setText("¿Olvidaste tu contraseña?");
        jbtnRecuperar.setBorder(null);
        jbtnRecuperar.setContentAreaFilled(false);
        jbtnRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnRecuperarMouseClicked(evt);
            }
        });
        jbtnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRecuperarActionPerformed(evt);
            }
        });
        jpLogin.add(jbtnRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 310, 30));

        jLabel7.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(75, 123, 125));
        jLabel7.setText("Usuario:");
        jpLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        getContentPane().add(jpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, -268, 470, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 123, 125), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPublic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/public2.jpg"))); // NOI18N
        jPanel1.add(jPublic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1010, 320));

        jPalo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/palito.png"))); // NOI18N
        jPanel1.add(jPalo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 418, 1000, 10));

        jPalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/palito.png"))); // NOI18N
        jPanel1.add(jPalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 94, 1000, 10));

        jPublic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/publi1.jpg"))); // NOI18N
        jPublic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jPublic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 320));

        jblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/borrar (1).png"))); // NOI18N
        jblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(jblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, -1, -1));

        jblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar (5).png"))); // NOI18N
        jblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(jblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         AnimationClass ac= new AnimationClass();
        ac.jLabelXLeft(0, -1000, 25, 5, jPublic);
        
        AnimationClass acc= new AnimationClass();
        acc.jLabelXRight(1000, 0, 25, 5, jPublic1);
        
    }//GEN-LAST:event_formWindowOpened
public void jPanelYUp(final int start, final int stop, final int delay, final int increment, final JPanel jPanel)
  {
    if (jPanel.getY() == start) {
      new Thread()
      {

        public void run()
        {
          while (jPanel.getY() > stop) {
            for (int i = start; i >= stop; i -= increment) {
              try
              {
                Thread.sleep(delay);
                jPanel.setLocation(jPanel.getX(), i);
              }
              catch (InterruptedException e)
              {
                System.out.println("Error Thread Interrupted: " + e);
              }
            }
          }
          jPanel.setLocation(jPanel.getX(), stop);
        }
      }.start();
    }
  }

public void jPanelYDown(final int start, final int stop, final int delay, final int increment, final JPanel jPanel)
  {
    if (jPanel.getY() == start) {
      new Thread()
      {

        public void run()
        {
          while (jPanel.getY() <= start) {
            for (int i = start; i <= stop; i += increment) {
              try
              {
                Thread.sleep(delay);
                
                jPanel.setLocation(jPanel.getX(), i);
              }
              catch (InterruptedException e)
              {
                System.out.println("Error Thread Interrupted: " + e);
              }
            }
          }
          jPanel.setLocation(jPanel.getX(), stop);
        }
      }.start();
    }
  }
    private void jbtnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEntrarMouseClicked
        String contrasenia = EncriptarContrasena.md5(jtxtContraseña.getText());
        try {
            // TODO add your handling code here:
            
            if(jtxtUsuario.getText().isEmpty() || jtxtContraseña.getText().isEmpty()){
                
                JOptionPane.showMessageDialog(null,"Campos Vacios", "ERROR",JOptionPane.ERROR_MESSAGE);
            }
            
            System.out.println(contrasenia);
            
            if(da.Validaracceso(cn.conectar(), jtxtUsuario.getText(), (contrasenia))==1){
                
        this.setVisible(false);
//        new Principal(jtxtUsuario.getText()).setVisible(true); // Main Form to show after the Login Form..
     Menu m = new Menu(jtxtUsuario.getText());m.setVisible(true); m.setExtendedState(MAXIMIZED_BOTH);
        m.setLocationRelativeTo(null);
//       JOptionPane.showMessageDialog(null, m);
            }
            else{
             JOptionPane.showMessageDialog(null,"Usuario o Password incorrectos", "ERROR",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbtnEntrarMouseClicked

    private void jbtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEntrarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbtnEntrarActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jtxtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtContraseñaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtContraseñaMouseClicked

    private void jbtnRecuperarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRecuperarMouseClicked
        // TODO add your handling code here:
        
        
          this.hide();
            new Verifica().show();
        
    }//GEN-LAST:event_jbtnRecuperarMouseClicked

    private void jbtnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRecuperarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRecuperarActionPerformed

    private void jpLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLoginMouseClicked
        // TODO add your handling code here:
        
        jPanelYDown(-268,0,25,5,jpLogin);
        jPanelYUp(0,-268,25,5,jpLogin);
    }//GEN-LAST:event_jpLoginMouseClicked

    private void jblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(Formularios.Login1.ICONIFIED);
    }//GEN-LAST:event_jblMinimizarMouseClicked

    private void jblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCerrarMouseClicked
        // TODO add your handling code here:
        try{
            int dialogButton=JOptionPane.YES_NO_OPTION;
            int result= JOptionPane.showConfirmDialog(this, "Seguro que desea salir","EXIT",dialogButton);
            if(result==0){
                System.exit(0);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jblCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jFondologin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jPalo;
    private javax.swing.JLabel jPalo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPublic;
    private javax.swing.JLabel jPublic1;
    private javax.swing.JLabel jblCerrar;
    private javax.swing.JLabel jblMinimizar;
    private javax.swing.JButton jbtnEntrar;
    private javax.swing.JButton jbtnRecuperar;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JPasswordField jtxtContraseña;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
